### ISSUE TITLE
Please update the Nuget package

### ISSUE THREAD

**Issue by jhoerr** [andyfmiller/LtiLibrary.Owin#5]
Hi Andy, it looks like the Consumer/Provider samples rely on some changes to `LtiLibrary.Owin.Security.Lti` and `LtiLibrary.AspNet.Identity.Owin` that have been made since the packages were last published in 2014. I'm unable to build the `LtiSamples` solution using the most recent versions of those packages (along with `LtiLibrary.Core` and `LtiLibrary.AspNet`). Would you consider publishing release versions of the packages that include the recent changes? Thanks!

**Comment by srijken** [comment]
+1

**Comment by andyfmiller** [comment]
@jhoerr , @srijken - I'm sorry for the confusion. The https://www.nuget.org/packages/LtiLibrary/ package is no longer being updated. It has been replaced with https://www.nuget.org/packages/LtiLibrary.Core/, https://www.nuget.org/packages/LtiLibrary.AspNet/, https://www.nuget.org/packages/LtiLibrary.Owin.Security.Lti/1.0.0-alpha, and https://www.nuget.org/packages/LtiLibrary.AspNet.Identity.Owin/1.0.0-alpha. This is explained in more detail here: http://andyfmiller.com/2015/03/01/ltilibrary-1-5/.

The solution file in LtiSamples tries to use the actual projects rather than the NuGet packages. The easiest way to the the LtiSamples running locally is to download both the LtiSamples and LtiLibrary solutions.
![solutionexplorer](https://cloud.githubusercontent.com/assets/2666882/13590851/51920684-e498-11e5-8e26-d6ead23d9c85.png)

**Comment by andyfmiller** [comment]
I added a Getting Started section to the [LtiSamples readme](https://github.com/andyfmiller/LtiSamples).
